# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs


#jobs:
#  build:
#    machine:
#      image: ubuntu-2204:current

#    steps:
#      - checkout
#      - run:
#          name: "Build_image"
#          command: docker build -t laeim/commetuveux:latest .

#      - run:
#          name: "Test curl"
#          command: |
#            docker run -d -p 8080:8080 --name LEZGO laeim/commetuveux:latest
#            sleep 15
#            curl http://localhost:8080

#      - run:
#          name: "Push DockerHub"
#          command: |
#            echo "$DOCKER_MDP" | docker login -u annoncebarre@gmail.com --password-stdin
#            docker push laeim/commetuveux:latest
      
orbs:
  docker: circleci/docker@2.8.2

workflows:
  build-and-publish-docker-image:
    jobs:
       - docker/publish:
          docker-password: DOCKER_MDP
          docker-username: DOCKER_USER
          image: laeim/commetuveux:latest
          tag:
            default: "1"

