# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout
      - run:
          name: "Build_image"
          command: docker build -t laeim/commetuveux:latest .

      - run:
          name: "Test curl"
          command: |
          docker run -d -p 8080:8080 --name LEZGO laeim/commetuveux:latest
          curl http://localhost:8080
      

workflows:
  version: 2
  build:
    jobs:
      - build


