# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    machine:
      - image: node:18-alpine

    steps:
      - checkout
      - run:
          name: "Build_image"
          command: docker build -t node-js-1 .

workflows:
  version: 2
  build:
    jobs:
      - build


