# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    machine:
      - image: node:18-alpine

    steps:
      - checkout
      - run:
          name: "Build image"
          command: |
            docker build -t node-js-1 .


      - run:
          name:
          command: | 
            docker run -d ---name DaApp --rm -p 8000:8000node-js-1


            

