
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout
      - run:
          - name: Build and push Docker images
              uses: docker/build-push-action@v6.13.0.

workflows:
  build-and-publish-docker-image:
    jobs:
       - docker/publish:
          docker-password: DOCKER_MDP
          docker-username: DOCKER_USER
          image: laeim/commetuveux
          tag: tagpersooklm



